name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  QUEUE_SERVER: queue_server
  NGINX_QUEUE: nginx_queue
  POLL_SERVER: poll_server
  REPO: temprepo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
       
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         
     - name: Build and push Docker image ${{ env.QUEUE_SERVER }}
       uses: docker/build-push-action@v2
       with:
          context: ./ds_queue
          file: ./ds_queue/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO }}:${{ env.QUEUE_SERVER }}
          pull: true
          push: true
    
     - name: Build and push Docker image ${{ env.NGINX_QUEUE }}
       uses: docker/build-push-action@v2
       with:
          context: ./ds_queue
          file: ./ds_queue/Dockerfile.nginx.queue
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO }}:${{ env.NGINX_QUEUE }}
          pull: true
          push: true
          
     - name: Build and push Docker image ${{ env.POLL_SERVER }}
       uses: docker/build-push-action@v2
       with:
          context: ./ds_poll
          file: ./ds_poll/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO }}:${{ env.POLL_SERVER }}
          pull: true
          push: true
    
